[package]
name = "riscv-vm"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]
default = ["logging"]

logging = ["dep:colored", "dep:log", "dep:fern"] # Enable for logging output

[dependencies]
bit_ops = "0.1.13"
bitfield = "0.17.0"
chrono = "0.4.38"

# logging
colored = { version = "2.1.0", optional = true }
log = { version = "0.4.22", optional = true }
fern = { version = "0.6.2", optional = true, features = ["colored"] }

[dependencies.riscv-decoder]
git = "https://github.com/RamenG0D/riscv-decoder.git"
